name: Deploy Order Service

on:
  push:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Unit Tests
        run: npm test

  # JOB 1: Build & Push (Runs on GitHub Cloud Servers - FREE CPU/RAM)
  build-and-push:
    needs: unit-test
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker Auth
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build & Push Docker Image
        run: |
          IMAGE="${{ secrets.GCP_AR_REPO }}/order-service:staging"
          docker build -t $IMAGE .
          docker push $IMAGE

  # JOB 2: Deploy (Runs on Staging VM)
  deploy:
    needs: build-and-push
    runs-on: [self-hosted, staging]
    environment: staging
    steps:

      - name: Pull and Restart Container
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCP_AR_REPO: ${{ secrets.GCP_AR_REPO }}
        run: |
          cd /opt/omni-infra/apps
          
          # Authenticate root docker with GCP Artifact Registry using Service Account Key
          echo "$GCP_SA_KEY" | sudo docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
          
          # Pull the new image and restart only order-service
          sudo docker compose -f docker-compose.yml pull order-service
          sudo docker compose -f docker-compose.yml up -d --no-deps order-service
          sudo docker image prune -f -a
